version: "3"
services:
  app:
    image: gabrielcamurcab/finance_auth
    container_name: "app_finance_auth_go"
    networks:
      - minha-rede

networks:
  minha-rede:
    external: true
